# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpd" do
  desc "A tool to declaratively manage Model Context Protocol (MCP) servers, providing a consistent interface to define and run tools across environments, from local development to containerized cloud deployments.
"
  homepage "https://github.com/mozilla-ai/mcpd"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpd"

  on_macos do
    on_intel do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.2/mcpd_Darwin_x86_64.tar.gz"
      sha256 "8344f60b9e347b03656a054ac9de113e864e9ad9cf96cebeb2d4917a9249dd8b"
    end
    on_arm do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.2/mcpd_Darwin_arm64.tar.gz"
      sha256 "d12f57910d1e29c1ef861c5c3813e69b6e7a7228dd1fdd0899ffda7e94c297ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.2/mcpd_Linux_x86_64.tar.gz"
      sha256 "396374ed2edc1dbedcf326911c7e3b8c0fa6b9eeb594b0d4d38adedd6720f79b"
    end
    on_arm do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.2/mcpd_Linux_arm64.tar.gz"
      sha256 "e1d1459a7d7012c5a354b83bdcc80a810718a652ff450fd2e9008592e64bd77c"
    end
  end

  conflicts_with formula: [
      "mcpd",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpd"]
    end
  end

  # No zap stanza required
end
