# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpd" do
  desc "A tool to declaratively manage Model Context Protocol (MCP) servers, providing a consistent interface to define and run tools across environments, from local development to containerized cloud deployments.
"
  homepage "https://github.com/mozilla-ai/mcpd"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpd"

  on_macos do
    on_intel do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.3/mcpd_Darwin_x86_64.tar.gz"
      sha256 "a7c8024da261e76d0f9d31f549c8109f5cea86bd80789c4d2666cdf56471646c"
    end
    on_arm do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.3/mcpd_Darwin_arm64.tar.gz"
      sha256 "d6a770e435f70da90c703aadcc63e2ec118800b9339648f74aa35662e5f59db7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.3/mcpd_Linux_x86_64.tar.gz"
      sha256 "71a5a2f5d4f6eeaa729364a89b5bed1c7a078a00912af85bcd7dfda3b1b874c4"
    end
    on_arm do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v0.0.3/mcpd_Linux_arm64.tar.gz"
      sha256 "456dad7c1486eebbad1e4811d6f496ab0b9fb57612119c6fd48f30825591046c"
    end
  end

  conflicts_with formula: [
      "mcpd",
    ]

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpd"]
    end
  end

  # No zap stanza required
end
